/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagestegano;

/**
 *
 * @author varun
 */
public class HideText extends javax.swing.JFrame {

    /**
     * Creates new form HideText
     */
    public HideText() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        chooseTextFileButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hideMessageTextArea = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spiralEmbeddingCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        alpha7CheckBox = new javax.swing.JCheckBox();
        alpha6CheckBox = new javax.swing.JCheckBox();
        alpha5CheckBox = new javax.swing.JCheckBox();
        alpha4CheckBox = new javax.swing.JCheckBox();
        alpha3CheckBox = new javax.swing.JCheckBox();
        alpha2CheckBox = new javax.swing.JCheckBox();
        alpha1CheckBox = new javax.swing.JCheckBox();
        alpha0CheckBox = new javax.swing.JCheckBox();
        red7CheckBox = new javax.swing.JCheckBox();
        red5CheckBox = new javax.swing.JCheckBox();
        red6CheckBox = new javax.swing.JCheckBox();
        red4CheckBox = new javax.swing.JCheckBox();
        red3CheckBox = new javax.swing.JCheckBox();
        red2CheckBox = new javax.swing.JCheckBox();
        red1CheckBox = new javax.swing.JCheckBox();
        red0CheckBox = new javax.swing.JCheckBox();
        green7CheckBox = new javax.swing.JCheckBox();
        green6CheckBox = new javax.swing.JCheckBox();
        green5CheckBox = new javax.swing.JCheckBox();
        green4CheckBox = new javax.swing.JCheckBox();
        green3CheckBox = new javax.swing.JCheckBox();
        green2CheckBox = new javax.swing.JCheckBox();
        green1CheckBox = new javax.swing.JCheckBox();
        green0CheckBox = new javax.swing.JCheckBox();
        blue6CheckBox = new javax.swing.JCheckBox();
        blue7CheckBox = new javax.swing.JCheckBox();
        blue5CheckBox = new javax.swing.JCheckBox();
        blue4CheckBox = new javax.swing.JCheckBox();
        blue3CheckBox = new javax.swing.JCheckBox();
        blue2CheckBox = new javax.swing.JCheckBox();
        blue1CheckBox = new javax.swing.JCheckBox();
        blue0CheckBox = new javax.swing.JCheckBox();
        hideTextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hide Text");

        jLabel2.setText("Choose a text File");

        chooseTextFileButton.setText("Choose text file");

        jLabel4.setText("OR");

        jLabel5.setText("Enter text to hide: ");

        jLabel6.setText("Use Spiral Embedding: ");

        spiralEmbeddingCheckBox.setText("spiral Embedding");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bit Planes"));
        jPanel1.setToolTipText("Bit Planes");

        jLabel7.setText("Alpha");

        jLabel8.setText("Red");

        jLabel9.setText("Green");

        jLabel10.setText("Blue");

        alpha7CheckBox.setText("7");

        alpha6CheckBox.setText("6");

        alpha5CheckBox.setText("5");

        alpha4CheckBox.setText("4");

        alpha3CheckBox.setText("3");

        alpha2CheckBox.setText("2");

        alpha1CheckBox.setText("1");

        alpha0CheckBox.setText("0");

        red7CheckBox.setText("7");

        red5CheckBox.setText("5");

        red6CheckBox.setText("6");

        red4CheckBox.setText("4");

        red3CheckBox.setText("3");

        red2CheckBox.setText("2");

        red1CheckBox.setText("1");

        red0CheckBox.setText("0");

        green7CheckBox.setText("7");

        green6CheckBox.setText("6");

        green5CheckBox.setText("5");

        green4CheckBox.setText("4");

        green3CheckBox.setText("3");

        green2CheckBox.setText("2");

        green1CheckBox.setText("1");

        green0CheckBox.setText("0");

        blue6CheckBox.setText("6");

        blue7CheckBox.setText("7");

        blue5CheckBox.setText("5");

        blue4CheckBox.setText("4");

        blue3CheckBox.setText("3");

        blue2CheckBox.setText("2");

        blue1CheckBox.setText("1");

        blue0CheckBox.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alpha7CheckBox)
                    .addComponent(red7CheckBox)
                    .addComponent(green7CheckBox)
                    .addComponent(blue7CheckBox))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alpha6CheckBox)
                    .addComponent(red6CheckBox)
                    .addComponent(green6CheckBox)
                    .addComponent(blue6CheckBox))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alpha5CheckBox)
                    .addComponent(red5CheckBox)
                    .addComponent(green5CheckBox)
                    .addComponent(blue5CheckBox))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alpha4CheckBox)
                    .addComponent(red4CheckBox)
                    .addComponent(green4CheckBox)
                    .addComponent(blue4CheckBox))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(blue3CheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blue2CheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(green3CheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(green2CheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alpha3CheckBox)
                        .addGap(26, 26, 26)
                        .addComponent(alpha2CheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(red3CheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(red2CheckBox)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alpha1CheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(alpha0CheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(red1CheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(red0CheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(green1CheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(green0CheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(blue1CheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(blue0CheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(alpha7CheckBox)
                    .addComponent(alpha6CheckBox)
                    .addComponent(alpha5CheckBox)
                    .addComponent(alpha4CheckBox)
                    .addComponent(alpha3CheckBox)
                    .addComponent(alpha2CheckBox)
                    .addComponent(alpha1CheckBox)
                    .addComponent(alpha0CheckBox))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(red7CheckBox)
                    .addComponent(red6CheckBox)
                    .addComponent(red5CheckBox)
                    .addComponent(red4CheckBox)
                    .addComponent(red3CheckBox)
                    .addComponent(red2CheckBox)
                    .addComponent(red1CheckBox)
                    .addComponent(red0CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(green7CheckBox)
                        .addComponent(green6CheckBox)
                        .addComponent(green5CheckBox)
                        .addComponent(green4CheckBox)
                        .addComponent(green3CheckBox)
                        .addComponent(green2CheckBox)
                        .addComponent(green1CheckBox)
                        .addComponent(green0CheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(blue6CheckBox)
                                .addComponent(blue7CheckBox))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(blue5CheckBox)
                                .addComponent(blue4CheckBox)
                                .addComponent(blue3CheckBox)
                                .addComponent(blue2CheckBox)
                                .addComponent(blue1CheckBox)
                                .addComponent(blue0CheckBox)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        hideTextButton.setText("Hide Text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel4)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(62, 62, 62)
                        .addComponent(hideMessageTextArea))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(73, 73, 73)
                                .addComponent(chooseTextFileButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(47, 47, 47)
                                .addComponent(spiralEmbeddingCheckBox)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(hideTextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chooseTextFileButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hideMessageTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spiralEmbeddingCheckBox))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hideTextButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HideText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HideText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HideText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HideText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HideText().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alpha0CheckBox;
    private javax.swing.JCheckBox alpha1CheckBox;
    private javax.swing.JCheckBox alpha2CheckBox;
    private javax.swing.JCheckBox alpha3CheckBox;
    private javax.swing.JCheckBox alpha4CheckBox;
    private javax.swing.JCheckBox alpha5CheckBox;
    private javax.swing.JCheckBox alpha6CheckBox;
    private javax.swing.JCheckBox alpha7CheckBox;
    private javax.swing.JCheckBox blue0CheckBox;
    private javax.swing.JCheckBox blue1CheckBox;
    private javax.swing.JCheckBox blue2CheckBox;
    private javax.swing.JCheckBox blue3CheckBox;
    private javax.swing.JCheckBox blue4CheckBox;
    private javax.swing.JCheckBox blue5CheckBox;
    private javax.swing.JCheckBox blue6CheckBox;
    private javax.swing.JCheckBox blue7CheckBox;
    private javax.swing.JButton chooseTextFileButton;
    private javax.swing.JCheckBox green0CheckBox;
    private javax.swing.JCheckBox green1CheckBox;
    private javax.swing.JCheckBox green2CheckBox;
    private javax.swing.JCheckBox green3CheckBox;
    private javax.swing.JCheckBox green4CheckBox;
    private javax.swing.JCheckBox green5CheckBox;
    private javax.swing.JCheckBox green6CheckBox;
    private javax.swing.JCheckBox green7CheckBox;
    private javax.swing.JTextField hideMessageTextArea;
    private javax.swing.JButton hideTextButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox red0CheckBox;
    private javax.swing.JCheckBox red1CheckBox;
    private javax.swing.JCheckBox red2CheckBox;
    private javax.swing.JCheckBox red3CheckBox;
    private javax.swing.JCheckBox red4CheckBox;
    private javax.swing.JCheckBox red5CheckBox;
    private javax.swing.JCheckBox red6CheckBox;
    private javax.swing.JCheckBox red7CheckBox;
    private javax.swing.JCheckBox spiralEmbeddingCheckBox;
    // End of variables declaration//GEN-END:variables
}
